### ISSUE TITLE
Flows have been changed after project switching

### ISSUE THREAD

**Issue by DmitrySidorow** [node-red/node-red#4044]
### Current Behavior

I have two similar projects, every switching I've got message "The flows on the server has been changed" 

this is a group:
![image](https://user-images.githubusercontent.com/43705385/216569362-af0ce31f-3fee-4f46-b788-b8668f35fcf3.png)

### Steps To Reproduce

create two projects which has groups and switch between them

### Environment

- Node-RED version: 3.0.1
- Node.js version: 16.19.0
- Platform/OS: Linux raspberrypi 5.15.84-v8+
- Browser: latest chrome

**Comment by DmitrySidorow** [comment]
> > create two projects which has groups and switch between them
> 
> 1. How are you switching projects?
>    
>    1. Are you using [projects mode](https://nodered.org/docs/user-guide/projects/)?
> 2. Do you have more than one browser open?
> 
> Please provide a more detailed step by step and I will see if I can recreate.
> 
> Thanks, Steve.
1) I use default project feauture
2) Only one browser and one tab

I can't reproduce it without my project which i can't provide :(
The problem is that for some reason property 'w' and 'h' is lost on some groups. But they exist in the project code
![image](https://user-images.githubusercontent.com/43705385/216594091-c336bf02-1211-4601-8601-279452a46b6e.png)

**Comment by Steve-Mcl** [comment]
> I use default project feauture

Sorry, I do not understand. "Project mode" is not a default feature. 
Can you please provide the STEP by STEP actions you take (I do not need a copy of your projects).

Something like...
1. Click hamburger Menu 
2. Click "Projects"
3. Click Open project
4. etc
5. etc

OR

Something like...
1. Stop Node-RED
2. rename flows.json to old.flows.json
3. rename orig-flows.json to flows.json
4. start Node-RED
5. etc
6. etc

This info is important to determine what you are seeing is a bug or mis-operation.

> The problem is that for some reason property 'w' and 'h' is lost on some groups. But they exist in the project code

Yeah, I see that, thanks for pointing that out. It is certainly a clue but I do really need to have a STEP BY STEP to be sure I see exactly what you see.


Thanks, Steve.

**Comment by DmitrySidorow** [comment]
> > I use default project feauture
> 
> Sorry, I do not understand. "Project mode" is not a default feature. Can you please provide the STEP by STEP actions you take (I do not need a copy of your projects).
> 
> Something like...
> 
> 1. Click hamburger Menu
> 2. Click "Projects"
> 3. Click Open project
> 4. etc
> 5. etc
> 
> OR
> 
> Something like...
> 
> 1. Stop Node-RED
> 2. rename flows.json to old.flows.json
> 3. rename orig-flows.json to flows.json
> 4. start Node-RED
> 5. etc
> 6. etc
> 
> This info is important to determine what you are seeing is a bug or mis-operation.
> 
> > The problem is that for some reason property 'w' and 'h' is lost on some groups. But they exist in the project code
> 
> Yeah, I see that, thanks for pointing that out. It is certainly a clue but I do really need to have a STEP BY STEP to be sure I see exactly what you see.
> 
> Thanks, Steve.

okay, finally i found reproducable way.
1) Create two node-red projects with default settings and imprort flows in one of them 
[flow.zip](https://github.com/node-red/node-red/files/10579233/flow.zip)
2) Switch to second empty project and then to the project into which the flows were imported
you will get 
![image](https://user-images.githubusercontent.com/43705385/216615512-3d5cfecc-45e6-4a96-8131-83166c8def0b.png)

**Comment by rvangeijtenbeek** [comment]
I've seen a comparable thing with the coordinates of a group. I've got a node-red Project, synched to a Bitbucket repo, and I run node-red on a Windows machine and in a Docker container (to make sure it works on Linux and Windows). I'm opening the editor in various browsers on Windows (mostly Edge and Firefox). I've only got one group in my flows, precisely because otherwise I would see changes that need to be merged all the time.

On the Docker system, only x and y are set. On the Windows system, w and h are also set. After pulling the latest changes to the Docker node-red, all four values are set. Then I make an unrelated change in another flow tab, deploy, and the width and height of the group is removed, showing as a difference when clicking on the flow.json in Project History > local files. Then I push that change to the repo, pull from the other system, and see the reverse happening.

**Comment by natcl** [comment]
We have the same issue and I don't think it's related to projects as we're not using projects. The w and h properties will oftentimes vanish making diffs less easy to read, example:
![image](https://github.com/node-red/node-red/assets/77556/edeb0fa1-998d-4439-9fe6-537336290caa)

**Comment by knolleary** [comment]
Fixed by #4426

**Comment by DmitrySidorow** [comment]
the problem still remains, every time I switch the project, a pop-up window appears that the threads have been changed, but no changes are visible in the diff
