### ISSUE TITLE
Bug(?) in trigger node 

### ISSUE THREAD

**Issue by franc-carter** [node-red/node-red#688]
Hi,

If my reading and testing correct (I'm very new to nodejs) then 89-trigger.js has a bug that means that new messages do not reset the timeout. this.extend on get compared to string values but it looks like the value it gets passed from the interface is a boolean and hence the test to see if it should extend the timeout always fails

**Comment by dceejay** [comment]
Is this not the same as already noted and fixed here ? 06731374a4f7e5a22aceda49cc0e1b9e9f475c75
and discussed here
https://mail.google.com/mail/u/0/#inbox/14e2bf7a0bcb2637

**Comment by franc-carter** [comment]
Hmm, yes - sorry. I'm not sure what I missed but I didn't (and still can't find an issue for this on github and the gmail link doesn't look like a google groups one)

Did I miss looking somewhere I should have ?

cheers

**Comment by franc-carter** [comment]
Race condition, I pulled the code down minutes before the fix was applied - sorry

**Comment by dceejay** [comment]
Hi - I have corrected the link to google groups above... 
Thanks for raising it. Not a problem - better safe than sorry ! 
(I guess technically we ought to raise and close an issue here also to document these sort of fixes)

**Comment by franc-carter** [comment]
On Fri, Jun 26, 2015 at 7:12 PM, Dave Conway-Jones <notifications@github.com
> wrote:

> Hi - I have corrected the link to google groups above...
>

Thanks, I'll start watching the group

cheers


> Thanks for raising it. Not a problem - better safe than sorry !
> (I guess technically we ought to raise and close an issue here also to
> document these sort of fixes)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-red/node-red/issues/688#issuecomment-115594068>.
>



-- 
Franc
